version: "3.3"
services:
  db:
    image: mysql:8.0.33
    networks:
      - iwillbag-network
    container_name: mysqldocker
    environment:
      MYSQL_DATABASE: iwillbag
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: iwb123
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - iwillbag-network
    container_name: ibag
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldocker:3306/iwillbag?useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: iwb123
    ports:
      - 8081:80
    restart: always
    
networks:
  iwillbag-network:
