server :
  port : 80
spring :
  thymeleaf :
    prefix : views/
    suffix : .html
    cache : false
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/green_db322
    username : greenUsr322
    password : pseongho235@
mybatis :
  type-aliases-package: bag.model
  configuration :
    map-underscore-to-camel-case : true
