server :
  port : 80
spring :
  thymeleaf :
    prefix : views/
    suffix : .html
    cache : false
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://db:3306/iwillbag?useUnicode=true&characterEncoding=UTF-8
    username : root
    password : iwb123
mybatis :
  type-aliases-package: bag.model
  configuration :
    map-underscore-to-camel-case : true
